### ISSUE TITLE
Package documentation on cache-control incorrect

### ISSUE THREAD

**Issue by NateWarner** [mpfdavis/outputcache#3]
The documentation in the README lists controlling the cache-control at a route level to use the following syntax:

```js
app.get('/api/:channel', xoc.middleware, api.middleware, (req, res) => {    
  res.set({'Cache-Control': 600});  
  res.json({hello:'world'}); //will be hit once every 10 minutes  
});
```

However, doing the above will cause the cache to always miss. Per line 109 in `outputcache.js`:

```js
if (!isSkipStatus && ttl.maxAge) {
```

It expects `maxAge` to exist on `ttl` and if it does not it will not cache the contents.

The method `parseCacheControl` does not parse out a number value from `cache-control` unless it is provided in the format of `max-age=number`.

If this is intended functionality, can you please update the documentation to instead look something closer to:

```js
app.get('/api/:channel', xoc.middleware, api.middleware, (req, res) => {    
  res.set({'Cache-Control': 'max-age=600'});  
  res.json({hello:'world'}); //will be hit once every 10 minutes  
});
```

Thank you for the helpful output-cache, btw!

**Comment by mpfdavis** [comment]
Fixed :)
