### ISSUE TITLE
Overloaded cache keys when using Express Router

### ISSUE THREAD

**Issue by abouthalf** [mpfdavis/outputcache#4]
Express Routers rewrite (nee remove) the mount point for the router.

Imagine two routers, each implementing a `/` route...

```javascript
const myModuleRoutes = require('./mymodule');
const yourModuleRoutes = require('./yourmodule');
app.use('/mymodule', myModuleRoutes);
app.use('/yourmoudle' yourModuleRoutes);
```
Based upon how Express handles routers and URLs this line here can create duplicate cache keys: https://github.com/mpfdavis/outputcache/blob/master/src/outputcache.js#L43

Recommend using `originalUrl` instead -> http://expressjs.com/en/api.html#req.originalUrl

**Comment by mpfdavis** [comment]
Fixed using express method - will check for existing key in upcoming rewrite.
